In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("amazon.csv")
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [7]:
df.shape

(1465, 16)

In [8]:
df.columns

Index(['product_id', 'product_name', 'category', 'discounted_price',
       'actual_price', 'discount_percentage', 'rating', 'rating_count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'img_link', 'product_link'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   str
 1   product_name         1465 non-null   str
 2   category             1465 non-null   str
 3   discounted_price     1465 non-null   str
 4   actual_price         1465 non-null   str
 5   discount_percentage  1465 non-null   str
 6   rating               1465 non-null   str
 7   rating_count         1463 non-null   str
 8   about_product        1465 non-null   str
 9   user_id              1465 non-null   str
 10  user_name            1465 non-null   str
 11  review_id            1465 non-null   str
 12  review_title         1465 non-null   str
 13  review_content       1465 non-null   str
 14  img_link             1465 non-null   str
 15  product_link         1465 non-null   str
dtypes: str(16)
memory usage: 183.3 KB

In [10]:
df.isnull().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           2
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df["discounted_price"] = df["discounted_price"].str.replace("₹", "", regex=False)
df["discounted_price"] = df["discounted_price"].str.replace(",", "", regex=False)
df["discounted_price"] = df["discounted_price"].astype(float)

df["actual_price"] = df["actual_price"].str.replace("₹", "", regex=False)
df["actual_price"] = df["actual_price"].str.replace(",", "", regex=False)
df["actual_price"] = df["actual_price"].astype(float)

In [13]:
df[["discounted_price", "actual_price"]].head()

   discounted_price  actual_price
0             399.0        1099.0
1             199.0         349.0
2             199.0        1899.0
3             329.0         699.0
4             154.0         399.0

In [14]:
df["discount_percentage"] = df["discount_percentage"].str.replace("%", "", regex=False)
df["discount_percentage"] = df["discount_percentage"].astype(float)

df["discount_percentage"].head()

0    64.0
1    43.0
2    90.0
3    53.0
4    61.0
Name: discount_percentage, dtype: float64

In [15]:
df["rating"] = pd.to_numeric(df["rating"], errors="coerce")

df["rating"].head()

0    4.2
1    4.0
2    3.9
3    4.2
4    4.2
Name: rating, dtype: float64

In [16]:
df["rating"].isnull().sum()

np.int64(1)

In [17]:
df["rating_count"] = df["rating_count"].str.replace(",", "", regex=False)
df["rating_count"] = df["rating_count"].astype(float)

df["rating_count"].head()

0    24269.0
1    43994.0
2     7928.0
3    94363.0
4    16905.0
Name: rating_count, dtype: float64

In [18]:
df["rating_count"].isnull().sum()

np.int64(2)

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   str
 1   product_name         1465 non-null   str
 2   category             1465 non-null   str
 3   discounted_price     1465 non-null   float64
 4   actual_price         1465 non-null   float64
 5   discount_percentage  1465 non-null   float64
 6   rating               1464 non-null   float64
 7   rating_count         1463 non-null   float64
 8   about_product        1465 non-null   str
 9   user_id              1465 non-null   str
 10  user_name            1465 non-null   str
 11  review_id            1465 non-null   str
 12  review_title         1465 non-null   str
 13  review_content       1465 non-null   str
 14  img_link             1465 non-null   str
 15  product_link         1465 non-null   str
dtypes: float64(5), str(11)
memory usage: 183.3 KB

In [20]:
df.describe()

,discounted_price,actual_price,discount_percentage,rating,rating_count
count,1465.000000,1465.000000,1465.000000,1464.000000,1463.000000
mean,3125.310874,5444.990635,47.691468,4.096585,18295.541353
std,6944.304394,10874.826864,21.635905,0.291674,42753.864952
min,39.000000,39.000000,0.000000,2.000000,2.000000
25%,325.000000,800.000000,32.000000,4.000000,1186.000000
50%,799.000000,1650.000000,50.000000,4.100000,5179.000000
75%,1999.000000,4295.000000,63.000000,4.300000,17336.500000
max,77990.000000,139900.000000,94.000000,5.000000,426973.000000

In [21]:
df[["discounted_price", "actual_price", "discount_percentage", "rating", "rating_count"]].describe()

,discounted_price,actual_price,discount_percentage,rating,rating_count
count,1465.000000,1465.000000,1465.000000,1464.000000,1463.000000
mean,3125.310874,5444.990635,47.691468,4.096585,18295.541353
std,6944.304394,10874.826864,21.635905,0.291674,42753.864952
min,39.000000,39.000000,0.000000,2.000000,2.000000
25%,325.000000,800.000000,32.000000,4.000000,1186.000000
50%,799.000000,1650.000000,50.000000,4.100000,5179.000000
75%,1999.000000,4295.000000,63.000000,4.300000,17336.500000
max,77990.000000,139900.000000,94.000000,5.000000,426973.000000

In [22]:
df["discount_value"] = df["actual_price"] - df["discounted_price"]

df[["actual_price", "discounted_price", "discount_value"]].head()

   actual_price  discounted_price  discount_value
0        1099.0             399.0           700.0
1         349.0             199.0           150.0
2        1899.0             199.0          1700.0
3         699.0             329.0           370.0
4         399.0             154.0           245.0

In [23]:
df[["product_name", "category", "actual_price", "discounted_price", "discount_value", "discount_percentage"]].sort_values(
    by="discount_value",
    ascending=False
).head(10)

,product_name,category,actual_price,discounted_price,discount_value,discount_percentage
249,Sony Bravia 164 cm (65 inches) 4K Ultra HD Sma...,"Electronics|HomeTheater,TV&Video|Televisions|S...",139900.0,77990.0,61910.0,44.0
1182,"Coway Professional Air Purifier for Home, Long...","Home&Kitchen|Heating,Cooling&AirQuality|AirPur...",59900.0,14400.0,45500.0,76.0
568,"Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...",Electronics|Mobiles&Accessories|Smartphones&Ba...,74999.0,37990.0,37009.0,49.0
150,VU 138 cm (55 inches) Premium Series 4K Ultra ...,"Electronics|HomeTheater,TV&Video|Televisions|S...",65000.0,29990.0,35010.0,54.0
1354,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,"Home&Kitchen|Heating,Cooling&AirQuality|AirCon...",75990.0,42990.0,33000.0,43.0
1306,ECOVACS DEEBOT N8 2-in-1 Robotic Vacuum Cleane...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",59900.0,27900.0,32000.0,53.0
283,LG 139 cm (55 inches) 4K Ultra HD Smart LED TV...,"Electronics|HomeTheater,TV&Video|Televisions|S...",79990.0,47990.0,32000.0,40.0
255,VU 164 cm (65 inches) The GloLED Series 4K Sma...,"Electronics|HomeTheater,TV&Video|Televisions|S...",85000.0,54990.0,30010.0,35.0
108,VU 139 cm (55 inches) The GloLED Series 4K Sma...,"Electronics|HomeTheater,TV&Video|Televisions|S...",65000.0,37999.0,27001.0,42.0
323,TCL 108 cm (43 inches) 4K Ultra HD Certified A...,"Electronics|HomeTheater,TV&Video|Televisions|S...",51990.0,24990.0,27000.0,52.0

In [24]:
df[["product_name", "category", "actual_price", "discounted_price", "discount_value", "discount_percentage"]].sort_values(
    by="discount_percentage",
    ascending=False
).head(10)

,product_name,category,actual_price,discounted_price,discount_value,discount_percentage
695,"rts [2 Pack] Mini USB C Type C Adapter Plug, T...",Computers&Accessories|Accessories&Peripherals|...,4999.0,294.0,4705.0,94.0
372,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",Electronics|WearableTechnology|SmartWatches,19999.0,1799.0,18200.0,91.0
380,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",Electronics|WearableTechnology|SmartWatches,19999.0,1799.0,18200.0,91.0
364,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",Electronics|WearableTechnology|SmartWatches,19999.0,1799.0,18200.0,91.0
368,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",Electronics|WearableTechnology|SmartWatches,19999.0,1799.0,18200.0,91.0
334,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",Electronics|WearableTechnology|SmartWatches,19999.0,1799.0,18200.0,91.0
557,LAPSTER 12pcs Spiral Cable Protectors for Char...,Electronics|Mobiles&Accessories|MobileAccessor...,999.0,99.0,900.0,90.0
920,"Silicone Rubber Earbuds Tips, Eartips, Earpads...","Electronics|Headphones,Earbuds&Accessories|Ear...",999.0,99.0,900.0,90.0
644,Sounce Spiral Charger Cable Protector Data Cab...,Computers&Accessories|Accessories&Peripherals|...,999.0,99.0,900.0,90.0
407,Sounce Spiral Charger Cable Protector Data Cab...,Computers&Accessories|Accessories&Peripherals|...,999.0,99.0,900.0,90.0

In [25]:
df["product_id"].nunique()

1351

In [26]:
df["product_name"].nunique()

1337

In [27]:
df["product_id"].value_counts().head(10)

product_id
B07JW9H4J1    3
B098NS6PVG    3
B096MSW6CT    3
B08HDJ86NZ    3
B08CF3B7N1    3
B08Y1TFSP6    3
B08WRWPM22    3
B08DDRGWTJ    3
B08CF3D7QR    3
B085DTN6R2    3
Name: count, dtype: int64

In [28]:
df["product_name"].value_counts().head(10)

product_name
Fire-Boltt Ninja Call Pro Plus 1.83" Smart Watch with Bluetooth Calling, AI Voice Assistance, 100 Sports Modes IP67 Rating, 240*280 Pixel High Resolution                                                  5
Fire-Boltt Phoenix Smart Watch with Bluetooth Calling 1.3",120+ Sports Modes, 240*240 PX High Res with SpO2, Heart Rate Monitoring & IP67 Rating                                                           4
Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)                                         3
Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black)          3
Sounce Fast Phone Charging Cable & Data Sync USB Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini & iOS Devices                                                                   3
boAt Deuce USB 300 2 in 1 Type-C & Micro USB Stress Resistant, Tangle-Free, Sturdy Cable with 3A Fast Charging & 480mbps Data Transmission, 10000+ Bends Lifespan and Extended 1.5m Length(Martian Red)    3
Portronics Konnect L 1.2M Fast Charging 3A 8 Pin USB Cable with Charge & Sync Function for iPhone, iPad (Grey)                                                                                             3
pTron Solero TB301 3A Type-C Data and Fast Charging Cable, Made in India, 480Mbps Data Sync, Strong and Durable 1.5-Meter Nylon Braided USB Cable for Type-C Devices for Charging Adapter (Black)          3
boAt Micro USB 55 Tangle-free, Sturdy Micro USB Cable with 3A Fast Charging & 480mbps Data Transmission (Black)                                                                                            3
MI Usb Type-C Cable Smartphone (Black)                                                                                                                                                                     3
Name: count, dtype: int64

In [29]:
df_produtos = df.drop_duplicates(subset="product_id")

df_produtos.shape

(1351, 17)

In [30]:
df_produtos["product_id"].nunique()

1351

In [32]:
df_produtos[["product_name", "category", "actual_price", "discounted_price", "discount_value", "discount_percentage"]].sort_values(
    by="discount_percentage",
    ascending=False
).head(10)

,product_name,category,actual_price,discounted_price,discount_value,discount_percentage
695,"rts [2 Pack] Mini USB C Type C Adapter Plug, T...",Computers&Accessories|Accessories&Peripherals|...,4999.0,294.0,4705.0,94.0
364,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",Electronics|WearableTechnology|SmartWatches,19999.0,1799.0,18200.0,91.0
368,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",Electronics|WearableTechnology|SmartWatches,19999.0,1799.0,18200.0,91.0
372,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",Electronics|WearableTechnology|SmartWatches,19999.0,1799.0,18200.0,91.0
380,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",Electronics|WearableTechnology|SmartWatches,19999.0,1799.0,18200.0,91.0
334,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",Electronics|WearableTechnology|SmartWatches,19999.0,1799.0,18200.0,91.0
407,Sounce Spiral Charger Cable Protector Data Cab...,Computers&Accessories|Accessories&Peripherals|...,999.0,99.0,900.0,90.0
1026,beatXP Kitchen Scale Multipurpose Portable Ele...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,1999.0,199.0,1800.0,90.0
2,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,1899.0,199.0,1700.0,90.0
602,LAPSTER Spiral Charger Spiral Charger Cable Pr...,Computers&Accessories|Accessories&Peripherals|...,999.0,99.0,900.0,90.0

In [3]:
import pandas as pd

df = pd.read_csv("amazon.csv")

In [4]:
df_produtos = df.drop_duplicates(subset="product_id")

df_produtos.shape

(1351, 16)

In [5]:
import pandas as pd

df = pd.read_csv("amazon.csv")

df["discounted_price"] = df["discounted_price"].str.replace("₹", "", regex=False)
df["discounted_price"] = df["discounted_price"].str.replace(",", "", regex=False)
df["discounted_price"] = df["discounted_price"].astype(float)

df["actual_price"] = df["actual_price"].str.replace("₹", "", regex=False)
df["actual_price"] = df["actual_price"].str.replace(",", "", regex=False)
df["actual_price"] = df["actual_price"].astype(float)

df["discount_percentage"] = df["discount_percentage"].str.replace("%", "", regex=False)
df["discount_percentage"] = df["discount_percentage"].astype(float)

df["rating"] = pd.to_numeric(df["rating"], errors="coerce")

df["rating_count"] = df["rating_count"].str.replace(",", "", regex=False)
df["rating_count"] = df["rating_count"].astype(float)

df["discount_value"] = df["actual_price"] - df["discounted_price"]

df_produtos = df.drop_duplicates(subset="product_id")

df_produtos.shape

(1351, 17)

In [6]:
df_produtos.groupby("category")[["discount_percentage", "discount_value", "rating", "rating_count"]].mean().sort_values(
    by="discount_percentage",
    ascending=False
).head(10)

,discount_percentage,discount_value,rating,rating_count
category,,,,
Computers&Accessories|Accessories&Peripherals|Cables&Accessories|CableConnectionProtectors,90.0,900.0,4.05,5073.5
"Electronics|Headphones,Earbuds&Accessories|Earpads",90.0,900.0,3.80,594.0
Electronics|Mobiles&Accessories|MobileAccessories|Décor|PhoneCharms,90.0,900.0,4.40,305.0
"Electronics|Headphones,Earbuds&Accessories|Adapters",88.0,879.0,3.90,6491.0
"Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboard&MiceAccessories|DustCovers",87.5,572.0,3.40,10462.5
Electronics|Mobiles&Accessories|MobileAccessories|Mounts|Shower&WallMounts,82.0,410.0,4.10,9340.0
Computers&Accessories|Components|InternalHardDrives,80.0,800.0,4.20,362.0
Computers&Accessories|Accessories&Peripherals|Adapters|USBtoUSBAdapters,78.5,2477.5,4.15,2983.0
Electronics|Mobiles&Accessories|MobileAccessories|Stands,76.4,630.0,4.16,13149.7
"Electronics|Headphones,Earbuds&Accessories|Cases",76.0,380.0,4.30,15032.0

In [7]:
df_produtos["main_category"] = df_produtos["category"].str.split("|").str[0]

df_produtos[["category", "main_category"]].head()

                                            category          main_category
0  Computers&Accessories|Accessories&Peripherals|...  Computers&Accessories
1  Computers&Accessories|Accessories&Peripherals|...  Computers&Accessories
2  Computers&Accessories|Accessories&Peripherals|...  Computers&Accessories
3  Computers&Accessories|Accessories&Peripherals|...  Computers&Accessories
4  Computers&Accessories|Accessories&Peripherals|...  Computers&Accessories

In [8]:
df_produtos.groupby("main_category")[["discount_percentage", "discount_value", "rating", "rating_count"]].mean().sort_values(
    by="discount_percentage",
    ascending=False
)

,discount_percentage,discount_value,rating,rating_count
main_category,,,,
HomeImprovement,57.500000,462.000000,4.250000,4283.000000
Computers&Accessories,53.224000,910.256693,4.153867,16984.388740
Health&PersonalCare,53.000000,1001.000000,4.000000,3663.000000
Electronics,49.906122,4192.214286,4.077755,28996.746939
MusicalInstruments,46.000000,709.000000,3.900000,44441.000000
Car&Motorbike,42.000000,1661.000000,3.800000,1118.000000
Home&Kitchen,40.120536,1831.458013,4.040716,6676.493304
OfficeProducts,12.354839,95.612903,4.309677,4828.225806
Toys&Games,0.000000,0.000000,4.300000,15867.000000

In [9]:
df_produtos["main_category"].value_counts()

main_category
Electronics              490
Home&Kitchen             448
Computers&Accessories    375
OfficeProducts            31
MusicalInstruments         2
HomeImprovement            2
Toys&Games                 1
Car&Motorbike              1
Health&PersonalCare        1
Name: count, dtype: int64